name: Deploy to GitHub Pages (No Artifact Upload)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Save current files to temp
        run: |
          mkdir ../temp-site
          cp -r * ../temp-site/
          cp -r .[^.]* ../temp-site/ || true  # Copy hidden files like .html or .well-known

      - name: Create orphan gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          rm -rf *

      - name: Restore site from temp folder
        run: |
          cp -r ../temp-site/* ./
          rm -rf ../temp-site

      - name: Setup Git user
        run: |
          git config --global user.name "Rishi Bot"
          git config --global user.email "rishi@example.com"

      - name: Commit and Push to gh-pages
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
