name: Deploy to GitHub Pages (No Artifact Upload)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config --global user.name "Rishi Bot"
          git config --global user.email "rishi@example.com"

      - name: Deploy to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          cp -r * .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
